version: 1.0.{build}

image: Visual Studio 2017

build:
  verbosity: detailed

environment:
  NUGET_KEY:
    secure: G45OD3ASmPDb+WoYqJ+FXzd43FYCWakr6EO720xMk2FU3nm1NtfmcWKM3/a8dBGP

cache:
  - '%USERPROFILE%\.nuget\packages -> paket.lock'

artifacts:
  - path: '**\Release\*.nupkg'

build_script:
  - cmd: fake build

for:
  - environment:
      APPVEYOR_REPO_TAG: true
    build_script:
      - cmd: fake build -t Publish
